---
namespace: yo_han
name: transip
version: 0.3.0
readme: README.md
authors:
  - Roald Nefs (github/roaldnefs)
  - Johan Kuijt (github/yo-han)
description: TransIP Ansible Collection.
license_file: COPYING
tags:
  - transip
  - cloud
repository: https://github.com/yo-han/ansible-collection-transip
#documentation: https://github.com/yo-han/ansible-collection-transip/tree/main/docs
homepage: https://github.com/yo-han/ansible-collection-transip
issues: https://github.com/yo-han/ansible-collection-transip/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - '*.tar.gz'
