---
namespace: roaldnefs
name: transip
version: 0.1.0
readme: README.md
authors:
  - Roald Nefs (github/roaldnefs)
description: TransIP Ansible Collection.
license_file: COPYING
tags:
  - transip
  - cloud
repository: https://github.com/roaldnefs/ansible-collection-transip
#documentation: https://github.com/roaldnefs/ansible-collection-transip/tree/main/docs
homepage: https://github.com/roaldnefs/ansible-collection-transip
issues: https://github.com/roaldnefs/ansible-collection-transip/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - '*.tar.gz'