---
name: Release
# on: 
#   release:
#     types:
#       - created
on:
  pull_request:
  push:
  schedule:
    - cron: '0 6 * * *'

env:
  NAMESPACE: roaldnefs
  COLLECTION_NAME: transip
  ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
  ANSIBLE_FORCE_COLOR: 1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Build the collection
        run: |
          ansible-galaxy collection build

      - name: Publish the collection
        run: |
          shopt -s extglob
          echo "ansible-galaxy collection publish ./${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-${GITHUB_REF/refs\/tags\/?(v)/}.tar.gz"
 